Add a set_timeout method for timers
stm32-rs/stm32h7xx-hal pull request #129
Opened 2020-08-27 23:03 UTC by dflemstr

I have a use-case where I need to set a specific timer timeout (using interrupts).

Of course it would be possible to convert the delay into a frequency, but then it would involve one division (delay -> Hz) and another one back (Hz -> delay).  It seemed more natural to support duration delays directly.

It might also make sense to use `CountDown<Time=Duration>` as well, but since there is already a `CountDown<Time=Hz>` I couldn't add a conflicting one.  However it might make sense to reconsider whether it makes sense to measure a duration in Hz, as is currently the case in this crate?

2020-08-28 06:59 UTC, hargoniX requested changes

2020-08-28 06:59 UTC, hargoniX commented on src/timer.rs
> +                pub fn set_timeout(&mut self, timeout: core::time::Duration) {
time::Duration might surely be a thing to look into, however as of now we usually use our self defined type Milliseconds from time.rs, probably we could look into replacing it with time::Duration though.

However as of now I'd prefer to keep the code consistent unless someone has a good point against it.

2020-08-28 07:00 UTC, hargoniX commented on src/timer.rs
> +                pub fn set_timeout(&mut self, timeout: core::time::Duration) {
In fact I would not be surprised if Rust could optimize these conversion lots of the time.

2020-08-28 20:46 UTC, richardeoin commented
Thanks for the PR! 

I'd agree with @hargoniX that that we should include the [`Milliseconds`](https://github.com/stm32-rs/stm32h7xx-hal/blob/master/src/time.rs#L23) type in this. I think the solution is to implement `Into<core::time::Duration> for Milliseconds` in [time.rs](https://github.com/stm32-rs/stm32h7xx-hal/blob/master/src/time.rs). In that case `set_timeout` could accept either `core::time::Duration` or `Milliseconds`.

I'd also suggest implementing `Into<core::time::Duration>` for all the frequency types. In that case it would be possible to swap over to `CountDown<Time=core::time::Duration>` without breaking any existing code.

Could the four lines `let psc = ...; let arr = ...;` go into their own private method? That would avoid the code duplication.

2020-08-30 12:15 UTC, dflemstr commented
I didn't notice the `Into<MilliSeconds> for Hertz` impl in time.rs, but for my use case I need sub-millisecond / more than 1000 Hz timers, so either of these approaches won't work for me unfortunately.  What would be your suggestion for an API that supports more than 1000 ticks per second/setting the timeout to <1ms?

2020-08-30 12:24 UTC, dflemstr commented
Maybe it could make sense to have a `Ticks<Clock>` type, to avoid having to perform the division more than once? Just a thought!

2020-08-30 13:30 UTC, richardeoin commented
It's clear that you need a sub-millisecond timeout, but that shouldn't mean writing an API that is broken for simpler use cases. Also bear in mind that for this HAL we're not worried about 1 or 2 integer divides, the usability of the API is much more important.

> What would be your suggestion for an API that supports more than 1000 ticks per second/setting the timeout to <1ms?

I explained this above. I'll just add it to the PR now to avoid confusion.

It's possible an intermediate type like `Ticks` might simplify things, it would be interesting to try.

2020-08-30 14:03 UTC, dflemstr commented
Now I understand what you meant, not sure how I misread it in hindsight, thanks!

2020-08-31 17:01 UTC, dflemstr commented
I'd prefer to merge this PR as is and perhaps try the `Ticks<..>` type as a separate PR if the integer division becomes a problem (which I doubt)!

2020-08-31 17:27 UTC, richardeoin commented
Agreed! @hargoniX feel free to merge this

2020-09-01 07:49 UTC, hargoniX commented
bors r+

2020-09-01 07:50 UTC, hargoniX commented
Or not i guess :p

2020-09-01 09:36 UTC, jordens commented
I added you through the stm32h7 team. Try again.

2020-09-01 09:48 UTC, hargoniX commented
bors r+

2020-09-01 09:56 UTC, merged

2020-09-01 10:06 UTC, hargoniX commented
Miracle!