Documentation improvements
stm32-rs/stm32h7xx-hal pull request #397
Opened 2022-10-25 16:18 UTC by richardeoin

* Add missing links to examples from docs
* Add a description to more examples
* Update some comments

2022-11-03 17:16 UTC, jordens requested changes
Otherwise LGTM.

2022-11-03 21:07 UTC, richardeoin commented on examples/adc.rs
> +//! Example of reading a voltage with ADC1 through DMA
Thanks for the review, indeed a typo

2022-11-04 16:44 UTC, jordens requested changes

2022-11-04 16:44 UTC, jordens commented on examples/adc_dma.rs
> +//! Example of reading ADC1 data using DMA1/2 through DMA
I think this was fine before

```suggestion
//! Example of reading ADC1 data using DMA1
```

2022-11-06 21:37 UTC, richardeoin commented on examples/adc_dma.rs
> +//! Example of reading ADC1 data using DMA1/2 through DMA
Thanks, corrected now

2022-11-06 21:43 UTC, richardeoin commented
bors r+

2022-11-06 21:50 UTC, merged