Bugfix for I2C read and writeread transactions
stm32-rs/stm32h7xx-hal pull request #402
Opened 2022-11-03 16:14 UTC by nkrackow

Simply wait until the busy flag is released. Now the stop condition occurs (right before the next start condition in the case of successive writereads). 
Fixes #401

2022-11-03 16:29 UTC, jordens requested changes
A changelog entry with a **Fixed** would be helpful for this.

2022-11-03 16:31 UTC, ryan-summers requested changes
Thanks for the PR! This indeed looks like a problematic bug.

- [ ] Please also add a CHANGELOG entry for the bug fix :)

2022-11-03 16:52 UTC, jordens commented on src/i2c.rs
> +                    busy_wait!(self.i2c, busy, is_not_busy);
Which functions of the traits do you have in mind? I can only see the `Write` trait. But yes, that should also wait for `!busy` after setting the STOP bit.

2022-11-03 17:02 UTC, ryan-summers commented on src/i2c.rs
> +                    busy_wait!(self.i2c, busy, is_not_busy);
Indeed, `Write` is all I'm referring to. It's also worth investigating if anything else is using `master_stop()` without awaiting STOP transmission.

2022-11-04 08:24 UTC, nkrackow commented on src/i2c.rs
> +                    busy_wait!(self.i2c, busy, is_not_busy);
I've added it to `write()`, I think that should be all now.

2022-11-04 08:49 UTC, jordens approved these changes

2022-11-04 09:15 UTC, ryan-summers approved these changes
LGTM. I reviewed the I2C module and could only identify these 3 locations that need the wait. Thanks for the fix :)

2022-11-04 09:16 UTC, merged